/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ru.zhenik.test.example.schema.avro.v1;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Word */
@org.apache.avro.specific.AvroGenerated
public class Word extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3600939610764121812L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Word\",\"namespace\":\"ru.zhenik.test.example.schema.avro.v1\",\"doc\":\"Word\",\"fields\":[{\"name\":\"payload\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Word payload\"}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Word> ENCODER =
      new BinaryMessageEncoder<Word>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Word> DECODER =
      new BinaryMessageDecoder<Word>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Word> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Word> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Word>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Word to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Word from a ByteBuffer. */
  public static Word fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Word payload */
  @Deprecated public java.lang.String payload;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Word() {}

  /**
   * All-args constructor.
   * @param payload Word payload
   */
  public Word(java.lang.String payload) {
    this.payload = payload;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return payload;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: payload = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'payload' field.
   * @return Word payload
   */
  public java.lang.String getPayload() {
    return payload;
  }

  /**
   * Sets the value of the 'payload' field.
   * Word payload
   * @param value the value to set.
   */
  public void setPayload(java.lang.String value) {
    this.payload = value;
  }

  /**
   * Creates a new Word RecordBuilder.
   * @return A new Word RecordBuilder
   */
  public static ru.zhenik.test.example.schema.avro.v1.Word.Builder newBuilder() {
    return new ru.zhenik.test.example.schema.avro.v1.Word.Builder();
  }

  /**
   * Creates a new Word RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Word RecordBuilder
   */
  public static ru.zhenik.test.example.schema.avro.v1.Word.Builder newBuilder(ru.zhenik.test.example.schema.avro.v1.Word.Builder other) {
    return new ru.zhenik.test.example.schema.avro.v1.Word.Builder(other);
  }

  /**
   * Creates a new Word RecordBuilder by copying an existing Word instance.
   * @param other The existing instance to copy.
   * @return A new Word RecordBuilder
   */
  public static ru.zhenik.test.example.schema.avro.v1.Word.Builder newBuilder(ru.zhenik.test.example.schema.avro.v1.Word other) {
    return new ru.zhenik.test.example.schema.avro.v1.Word.Builder(other);
  }

  /**
   * RecordBuilder for Word instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Word>
    implements org.apache.avro.data.RecordBuilder<Word> {

    /** Word payload */
    private java.lang.String payload;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ru.zhenik.test.example.schema.avro.v1.Word.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.payload)) {
        this.payload = data().deepCopy(fields()[0].schema(), other.payload);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Word instance
     * @param other The existing instance to copy.
     */
    private Builder(ru.zhenik.test.example.schema.avro.v1.Word other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.payload)) {
        this.payload = data().deepCopy(fields()[0].schema(), other.payload);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'payload' field.
      * Word payload
      * @return The value.
      */
    public java.lang.String getPayload() {
      return payload;
    }

    /**
      * Sets the value of the 'payload' field.
      * Word payload
      * @param value The value of 'payload'.
      * @return This builder.
      */
    public ru.zhenik.test.example.schema.avro.v1.Word.Builder setPayload(java.lang.String value) {
      validate(fields()[0], value);
      this.payload = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'payload' field has been set.
      * Word payload
      * @return True if the 'payload' field has been set, false otherwise.
      */
    public boolean hasPayload() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'payload' field.
      * Word payload
      * @return This builder.
      */
    public ru.zhenik.test.example.schema.avro.v1.Word.Builder clearPayload() {
      payload = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Word build() {
      try {
        Word record = new Word();
        record.payload = fieldSetFlags()[0] ? this.payload : (java.lang.String) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Word>
    WRITER$ = (org.apache.avro.io.DatumWriter<Word>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Word>
    READER$ = (org.apache.avro.io.DatumReader<Word>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
